app :
  UPLOAD_FOLDER : uploads
  RESULTS_FOLDER : results
  DOWNLOAD_FOLDER : downloads
  logs_file :
    path : app.log
    max_logged_size : 10485760  #----- 10 * 1024 * 1024  --> 10MB
    max_kept_size : 102400  #----- 100 * 1024  --> 100KB


env :
  selected : "1"


google_login :
  scopes : ["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email", "openid"]

google_cloud :
  client_secrets_file : config/secrets/google_cloud/client_secret_ifresh.json
  configs_file : config/secrets/google_cloud/configs.json

gemini_google :
  google_api_key_file : config/secrets/gemini_google/google_api_key.json


firebase_google :
  service_account_keys_file : config/secrets/firebase_google/ifresh-firebase-adminsdk.json
  firebase_config_file : config/secrets/firebase_google/ifresh_firebaseConfig.json